// Typelizer digest afc511c042fbdc2c2f0e158080e2a47b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminExport = {
  id: string;
  number: string;
  type: string | null;
  format: string | null;
  created_at: string;
  updated_at: string;
  user_id: string | null;
  done: boolean;
  filename: string | null;
  byte_size: number | null;
  download_url: string | null;
}

export default PallasTradeApiV3AdminExport;
