// Typelizer digest 94aa73456ba86fca87fd6922b0f75fad
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Digital = {
  id: string;
  created_at: string;
  updated_at: string;
  variant_id: string | null;
}

export default PallasTradeApiV3Digital;
