// Typelizer digest b781f1dcfbb22d2050eb134c3eba19d0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3BackInStockSubscription = {
  id: string;
  product_id: string | null;
  email: string;
  status: string;
  created_at: string;
}

export default PallasTradeApiV3BackInStockSubscription;
