// Typelizer digest c63c3594791a446741152b58e3a92958
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminState = {
  abbr: string;
  name: string;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminState;
