// Typelizer digest 5685160ef0f3c23297175fb46f59fc66
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3CustomField} from '@/types'

type PallasTradeApiV3Category = {
  id: string;
  name: string;
  permalink: string;
  position: number;
  depth: number;
  meta_title: string | null;
  meta_description: string | null;
  meta_keywords: string | null;
  children_count: number;
  parent_id: string | null;
  description: string;
  description_html: string;
  image_url: string | null;
  square_image_url: string | null;
  is_root: boolean;
  is_child: boolean;
  is_leaf: boolean;
  parent?: PallasTradeApiV3Category;
  children?: Array<PallasTradeApiV3Category>;
  ancestors?: Array<PallasTradeApiV3Category>;
  custom_fields?: Array<PallasTradeApiV3CustomField>;
}

export default PallasTradeApiV3Category;
