// Typelizer digest a6082d456e0a406efb03001295053656
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminStockLocation = {
  id: string;
  state_abbr: string | null;
  name: string;
  address1: string | null;
  city: string | null;
  zipcode: string | null;
  country_iso: string | null;
  country_name: string | null;
  state_text: string | null;
  admin_name: string | null;
  address2: string | null;
  state_name: string | null;
  phone: string | null;
  company: string | null;
  active: boolean;
  default: boolean;
  backorderable_default: boolean;
  propagate_all_variants: boolean;
  kind: string;
  pickup_enabled: boolean;
  pickup_stock_policy: string;
  pickup_ready_in_minutes: number | null;
  pickup_instructions: string | null;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminStockLocation;
