// Typelizer digest b7564466d4e3944eaeb47d9f5a6774af
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminPaymentMethod = {
  id: string;
  name: string;
  description: string | null;
  type: string;
  kind: string;
  frontend_kind: string;
  session_required: boolean;
  source_required: boolean;
  metadata: Record<string, unknown>;
  active: boolean;
  auto_capture: boolean | null;
  storefront_visible: boolean;
  position: number;
  created_at: string;
  updated_at: string;
  preferences: Record<string, unknown>;
  preference_schema: Array<{ key: string; type: string; default: unknown }>;
  optionized: boolean;
  options: Array<{ kind: string; name: string; frontend_kind: string; active: boolean; position: number }>;
}

export default PallasTradeApiV3AdminPaymentMethod;
