// Typelizer digest 8d2c0ef38b83199b9f92c1b6b8b95ddb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminEmailLog = {
  id: string;
  mailer: string;
  action: string;
  to: string;
  from: string | null;
  subject: string | null;
  status: string;
  error: string | null;
  sent_at: string;
  created_at: string;
}

export default PallasTradeApiV3AdminEmailLog;
