// Typelizer digest fc808d44f0e1e9592cfec49e6fca7dd6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3DeliveryMethod = {
  id: string;
  name: string;
  code: string | null;
  display_estimated_price: string | null;
  estimated_transit_business_days_min: number | null;
  estimated_transit_business_days_max: number | null;
}

export default PallasTradeApiV3DeliveryMethod;
