// Typelizer digest a4377e0836904b78da67c806d1a2bf70
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminOptionValue} from '@/types'

type PallasTradeApiV3AdminOptionType = {
  id: string;
  name: string;
  label: string;
  position: number;
  kind: string;
  translations?: Record<string, Record<string, string | number | null>>;
  metadata: Record<string, unknown>;
  filterable: boolean;
  created_at: string;
  updated_at: string;
  option_values?: Array<PallasTradeApiV3AdminOptionValue>;
}

export default PallasTradeApiV3AdminOptionType;
