// Typelizer digest 4244456a3ce7a02f8f6a340984294764
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Policy = {
  id: string;
  name: string;
  slug: string;
  body: string | null;
  body_html: string | null;
  merchant_return_policy: { category: string, days: number | null, method: string | null, fees: string | null, countries: string[] } | null;
}

export default PallasTradeApiV3Policy;
