// Typelizer digest 84b202f48c4807a9f1cdcb521f06c1fb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminPromotionAction = {
  id: string;
  created_at: string;
  updated_at: string;
  type: string;
  promotion_id: string;
  preferences: Record<string, unknown>;
  preference_schema: Array<{ key: string; type: string; default: unknown }>;
  label: string;
  calculator: { type: string; label: string; preferences: Record<string, unknown>; preference_schema: Array<{ key: string; type: string; default: unknown }> } | null;
  line_items: Array<{ variant_id: string; quantity: number }> | null;
}

export default PallasTradeApiV3AdminPromotionAction;
