// Typelizer digest 72402cea813d17ab815cb5750b9e5f05
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminEmailTemplate = {
  id: string;
  key: string;
  name: string;
  subject: string;
  body_html: string | null;
  body_text: string | null;
  placeholders: string | null;
  active: boolean;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminEmailTemplate;
