// Typelizer digest b5f8c9605ad8301055ed22147f7a4aaf
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {CreditCard, StoreCredit, PaymentSource, PallasTradeApiV3PaymentMethod} from '@/types'

type PallasTradeApiV3Payment = {
  id: string;
  payment_method_id: string;
  response_code: string | null;
  number: string;
  amount: string | null;
  display_amount: string | null;
  status: string;
  source_type: 'credit_card' | 'store_credit' | 'payment_source' | null;
  source_id: string | null;
  source: CreditCard | StoreCredit | PaymentSource | null;
  payment_method: PallasTradeApiV3PaymentMethod;
}

export default PallasTradeApiV3Payment;
