// Typelizer digest 7b1f4698e0f6e303be7ca580d6bf480f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminProductPublication = {
  id: string;
  published_at: string | null;
  unpublished_at: string | null;
  product_id: string;
  channel_id: string;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminProductPublication;
