// Typelizer digest 45d9209cb5dcd701c4abfc799385e509
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminAddress = {
  id: string;
  first_name: string | null;
  last_name: string | null;
  full_name: string;
  address1: string | null;
  address2: string | null;
  postal_code: string | null;
  city: string | null;
  phone: string | null;
  company: string | null;
  country_name: string;
  country_iso: string;
  state_text: string | null;
  state_abbr: string | null;
  quick_checkout: boolean;
  is_default_billing: boolean;
  is_default_shipping: boolean;
  state_name: string | null;
  label: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  customer_id: string | null;
}

export default PallasTradeApiV3AdminAddress;
