// Typelizer digest 2c59f4bf6ebc392de4aced379c302216
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Import = {
  id: string;
  number: string;
  type: string | null;
  rows_count: number;
  created_at: string;
  updated_at: string;
  status: string;
  owner_type: string | null;
  owner_id: string | null;
  user_id: string | null;
}

export default PallasTradeApiV3Import;
