// Typelizer digest 70dac3623dc4a960cccd9bea9f52d26c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Market, PallasTradeApiV3AdminState} from '@/types'

type PallasTradeApiV3AdminCountry = {
  iso: string;
  iso3: string;
  name: string;
  states_required: boolean;
  zipcode_required: boolean;
  states?: Array<PallasTradeApiV3AdminState>;
  market?: Market | null;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminCountry;
