// Typelizer digest df94dcf0e20bed5e1a6ca4aeebf9f832
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3PaymentMethod = {
  id: string;
  name: string;
  description: string | null;
  type: string;
  kind: string;
  frontend_kind: string;
  session_required: boolean;
  option_id: string;
  group: string;
  position: number;
  entries: Array<{ option_id: string, method_key: string, display_name: string, frontend_kind: string, group: string, position: number }>;
  method_key: string;
  display_name: string;
  source_required: boolean;
  client_config: { provider: string, environment: string | null, publishable: Record<string, string>, session_token: string | null };
}

export default PallasTradeApiV3PaymentMethod;
