// Typelizer digest 7266e41c1ce064db3a745dc6a87ea552
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Report = {
  id: string;
  type: string | null;
  currency: string | null;
  user_id: string | null;
  date_from: string | null;
  date_to: string | null;
}

export default PallasTradeApiV3Report;
