// Typelizer digest bedaba52cf768c152a827a7982a5343e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Refund = {
  id: string;
  transaction_id: string | null;
  amount: string | null;
  payment_id: string | null;
  refund_reason_id: string | null;
  reimbursement_id: string | null;
}

export default PallasTradeApiV3Refund;
