// Typelizer digest 5bf8bcfefc7b30cef425e63880d686dc
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Export = {
  id: string;
  number: string;
  type: string | null;
  format: string | null;
  created_at: string;
  updated_at: string;
  user_id: string | null;
}

export default PallasTradeApiV3Export;
