// Typelizer digest 5deeb17dbabe69cdaf0fc1763df73c9d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminPriceRule} from '@/types'

type PallasTradeApiV3AdminPriceList = {
  id: string;
  name: string;
  description: string | null;
  status: string;
  position: number;
  match_policy: string;
  starts_at: string | null;
  ends_at: string | null;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
  currently_active: boolean;
  products_count: number;
  prices_count: number;
  product_ids: Array<string>;
  price_rules?: Array<PallasTradeApiV3AdminPriceRule>;
}

export default PallasTradeApiV3AdminPriceList;
