// Typelizer digest d6d04374f743d20f8fdd555204cfedc4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminAddress, PallasTradeApiV3AdminOrder, PallasTradeApiV3AdminStoreCredit, PallasTradeApiV3AdminCustomerGroup} from '@/types'

type PallasTradeApiV3AdminCustomer = {
  id: string;
  email: string;
  first_name: string | null;
  last_name: string | null;
  phone: string | null;
  accepts_email_marketing: boolean;
  full_name: string;
  available_store_credit_total: string;
  display_available_store_credit_total: string;
  addresses?: Array<PallasTradeApiV3AdminAddress>;
  default_billing_address?: PallasTradeApiV3AdminAddress | null;
  default_shipping_address?: PallasTradeApiV3AdminAddress | null;
  login: string | null;
  metadata: Record<string, unknown>;
  last_sign_in_at: string | null;
  current_sign_in_at: string | null;
  created_at: string;
  updated_at: string;
  sign_in_count: number;
  failed_attempts: number;
  last_sign_in_ip: string | null;
  current_sign_in_ip: string | null;
  tags: Array<string>;
  internal_note_html: string | null;
  default_billing_address_id: string | null;
  default_shipping_address_id: string | null;
  orders_count: number;
  total_spent: string;
  display_total_spent: string;
  last_order_completed_at: string | null;
  orders?: Array<PallasTradeApiV3AdminOrder>;
  store_credits?: Array<PallasTradeApiV3AdminStoreCredit>;
  customer_group_ids: Array<string>;
  customer_groups?: Array<PallasTradeApiV3AdminCustomerGroup>;
}

export default PallasTradeApiV3AdminCustomer;
