// Typelizer digest 9e3b74722e54dd881004cb5d7ad09e2d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminPaymentMethod = {
  id: string;
  name: string;
  description: string | null;
  type: string;
  kind: string;
  frontend_kind: string;
  session_required: boolean;
  option_id: string;
  method_key: string;
  display_name: string;
  source_required: boolean;
  client_config: { provider: string, environment: string | null, publishable: Record<string, string>, session_token: string | null };
  metadata: Record<string, unknown>;
  active: boolean;
  auto_capture: boolean | null;
  storefront_visible: boolean;
  position: number;
  environment: string;
  created_at: string;
  updated_at: string;
  preferences: Record<string, unknown>;
  preference_schema: Array<{ key: string; type: string; default: unknown }>;
  credential_status: Array<{ key: string; level: string; rotated_at: string | null; expires_on: string | null; days_left: number | null; alert_level: string }>;
  optionized: boolean;
  options: Array<{ kind: string; name: string; frontend_kind: string; active: boolean; position: number; rule_set: Record<string, unknown> | null; scope_summary: string }>;
}

export default PallasTradeApiV3AdminPaymentMethod;
