// Typelizer digest 827b9d41efe7ec3de2cd5b5ceb0a1f1f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminWebhookDelivery = {
  id: string;
  event_name: string;
  event_id: string | null;
  response_code: number | null;
  execution_time: number | null;
  error_type: string | null;
  request_errors: string | null;
  response_body: string | null;
  success: boolean | null;
  payload: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  delivered_at: string | null;
  webhook_endpoint_id: string;
  webhook_endpoint_url: string;
}

export default PallasTradeApiV3AdminWebhookDelivery;
