// Typelizer digest 33096244ae59966ec674fc84389ab0a8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminPriceHistory = {
  id: string;
  amount: string;
  amount_in_cents: number;
  currency: string;
  display_amount: string;
  recorded_at: string;
  variant_id: string;
  price_id: string;
  compare_at_amount: string | null;
  created_at: string;
}

export default PallasTradeApiV3AdminPriceHistory;
