// Typelizer digest 049abf0db14184b3617464e9b997831d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3OptionType = {
  id: string;
  name: string;
  label: string;
  position: number;
  kind: string;
}

export default PallasTradeApiV3OptionType;
