// Typelizer digest f3490b60231a2614a2530364c508e48b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3DeliveryMethod = {
  id: string;
  name: string;
  code: string | null;
  display_estimated_price: string | null;
}

export default PallasTradeApiV3DeliveryMethod;
