// Typelizer digest 2e3d536d4f4e081bd8b031612770d623
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminApiKey = {
  id: string;
  name: string;
  key_type: string;
  token_prefix: string | null;
  scopes: Array<string>;
  created_at: string;
  updated_at: string;
  revoked_at: string | null;
  last_used_at: string | null;
  plaintext_token: string | null;
  created_by_email: string | null;
}

export default PallasTradeApiV3AdminApiKey;
