// Typelizer digest 6e8ebc992f18a9ebe145e235abeb05dc
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminAdminUser = {
  id: string;
  email: string;
  first_name: string | null;
  last_name: string | null;
  full_name: string | null;
  selected_locale: string | null;
  created_at: string;
  updated_at: string;
  avatar_url: string | null;
  roles: Array<{ id: string; name: string }>;
}

export default PallasTradeApiV3AdminAdminUser;
