// Typelizer digest 9cc4f2e4a9ba6c693ca3bcc6636299ec
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Asset = {
  id: string;
  viewable_id: string;
  type: string | null;
  viewable_type: string;
  position: number | null;
  alt: string | null;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3Asset;
