// Typelizer digest 85f2594dcf958f821a54ec99f2069c07
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Currency = {
  iso_code: string;
  name: string;
  symbol: string;
}

export default PallasTradeApiV3Currency;
