// Typelizer digest 04b2be4c504ce00006c0fbe6bc6bc2ee
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Market, PallasTradeApiV3State} from '@/types'

type PallasTradeApiV3Country = {
  iso: string;
  iso3: string;
  name: string;
  states_required: boolean;
  zipcode_required: boolean;
  states?: Array<PallasTradeApiV3State>;
  market?: Market | null;
}

export default PallasTradeApiV3Country;
