// Typelizer digest be87a3a9c72bf181cd35f587afbe4fd9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3StockMovement = {
  id: string;
  quantity: number;
  action: string | null;
  originator_type: string | null;
  created_at: string;
  updated_at: string;
  originator_id: string | null;
  stock_item_id: string | null;
}

export default PallasTradeApiV3StockMovement;
