// Typelizer digest 77f2584fb77915125a6d5d2cf6e7a9d0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminOptionType} from '@/types'

type PallasTradeApiV3AdminOptionValue = {
  id: string;
  option_type_id: string;
  name: string;
  label: string;
  position: number;
  color_code: string | null;
  option_type_name: string;
  option_type_label: string;
  image_url: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  option_type?: PallasTradeApiV3AdminOptionType;
}

export default PallasTradeApiV3AdminOptionValue;
