// Typelizer digest 30739d0039cde6c9b32291c9509ad0f9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminAdjustment = {
  id: string;
  label: string;
  display_amount: string;
  included: boolean;
  created_at: string;
  updated_at: string;
  amount: string;
  order_id: string | null;
}

export default PallasTradeApiV3AdminAdjustment;
