// Typelizer digest aaf4121b32cd24244c2b6562ce449bcf
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3PaymentSource = {
  id: string;
  gateway_payment_profile_id: string | null;
}

export default PallasTradeApiV3PaymentSource;
