// Typelizer digest 4f775ae1b8aeacc14ee352b4f0604ff7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminSetupTask = {
  name: string;
  done: boolean;
}

export default PallasTradeApiV3AdminSetupTask;
