// Typelizer digest 388bd54bf936fcfbd3b4e4c09cfde4d3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminOrder} from '@/types'

type PallasTradeApiV3AdminReimbursement = {
  id: string;
  number: string;
  reimbursement_status: string | null;
  total: string | null;
  order_id: string | null;
  customer_return_id: string | null;
  created_at: string;
  updated_at: string;
  order?: PallasTradeApiV3AdminOrder;
}

export default PallasTradeApiV3AdminReimbursement;
