// Typelizer digest 2887af51c1c7b54631538a27ccd100c6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Channel = {
  id: string;
  name: string;
  code: string;
  active: boolean;
  default: boolean;
}

export default PallasTradeApiV3Channel;
