// Typelizer digest b5df20543d0ce5a4174d4c215a1a68ce
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3StockTransfer = {
  id: string;
  number: string | null;
  type: string | null;
  reference: string | null;
  created_at: string;
  updated_at: string;
  source_location_id: string | null;
  destination_location_id: string | null;
}

export default PallasTradeApiV3StockTransfer;
