// Typelizer digest 52bac5fafad4ac389d6072dffe52104e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminOptionValue, PallasTradeApiV3AdminDigitalLink, PallasTradeApiV3AdminVariant, PallasTradeApiV3AdminTaxCategory, PallasTradeApiV3AdminAdjustment} from '@/types'

type PallasTradeApiV3AdminLineItem = {
  id: string;
  variant_id: string;
  preorder: boolean;
  preorder_ships_at: string | null;
  quantity: number;
  currency: string;
  name: string;
  slug: string;
  options_text: string;
  price: string;
  display_price: string;
  total: string;
  display_total: string;
  adjustment_total: string;
  display_adjustment_total: string;
  additional_tax_total: string;
  display_additional_tax_total: string;
  included_tax_total: string;
  display_included_tax_total: string;
  discount_total: string;
  display_discount_total: string;
  pre_tax_amount: string;
  display_pre_tax_amount: string;
  discounted_amount: string;
  display_discounted_amount: string;
  display_compare_at_amount: string | null;
  compare_at_amount: string | null;
  thumbnail_url: string | null;
  option_values: Array<PallasTradeApiV3AdminOptionValue>;
  digital_links: Array<PallasTradeApiV3AdminDigitalLink>;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  cost_price: string | null;
  tax_category_id: string | null;
  variant?: PallasTradeApiV3AdminVariant;
  tax_category?: PallasTradeApiV3AdminTaxCategory;
  adjustments?: Array<PallasTradeApiV3AdminAdjustment>;
}

export default PallasTradeApiV3AdminLineItem;
