// Typelizer digest b83b9150c9630d98f939b8eec456ceb4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3CustomerReturn = {
  id: string;
  number: string;
  created_at: string;
  updated_at: string;
  stock_location_id: string | null;
}

export default PallasTradeApiV3CustomerReturn;
