// Typelizer digest 91435576bcd0b1183a291ba5ca5775b1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Price, PriceHistory, PallasTradeApiV3AdminMedia, PallasTradeApiV3AdminVariant, PallasTradeApiV3AdminOptionType, PallasTradeApiV3AdminOptionValue, PallasTradeApiV3AdminCategory, PallasTradeApiV3AdminCustomField, PallasTradeApiV3AdminProductPublication, PallasTradeApiV3AdminChannel} from '@/types'

type PallasTradeApiV3AdminProduct = {
  id: string;
  name: string;
  slug: string;
  meta_title: string | null;
  meta_description: string | null;
  meta_keywords: string | null;
  variant_count: number;
  available_on: string | null;
  preorder_ships_at: string | null;
  purchasable: boolean;
  preorder: boolean;
  in_stock: boolean;
  backorderable: boolean;
  available: boolean;
  description: string | null;
  description_html: string | null;
  default_variant_id: string;
  thumbnail_url: string | null;
  tags: Array<string>;
  average_rating: number | null;
  review_count: number;
  price: Price | null;
  original_price: Price | null;
  primary_media?: PallasTradeApiV3AdminMedia;
  media?: Array<PallasTradeApiV3AdminMedia>;
  variants?: Array<PallasTradeApiV3AdminVariant>;
  default_variant?: PallasTradeApiV3AdminVariant;
  option_types?: Array<PallasTradeApiV3AdminOptionType>;
  option_values?: Array<PallasTradeApiV3AdminOptionValue>;
  categories?: Array<PallasTradeApiV3AdminCategory>;
  custom_fields?: Array<PallasTradeApiV3AdminCustomField>;
  prior_price?: PriceHistory | null;
  translations?: Record<string, Record<string, string | number | null>>;
  status: string;
  metadata: Record<string, unknown>;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
  tax_category_id: string | null;
  product_publications?: Array<PallasTradeApiV3AdminProductPublication>;
  channels?: Array<PallasTradeApiV3AdminChannel>;
}

export default PallasTradeApiV3AdminProduct;
