// Typelizer digest b44922e6db1b0ec9d31ff9775fdf4ee7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {CartItem, PallasTradeApiV3Address, PallasTradeApiV3PaymentMethod} from '@/types'

type PallasTradeApiV3ShoppingCart = {
  id: string;
  token: string;
  status: string;
  email: string | null;
  customer_note: string | null;
  currency: string;
  locale: string | null;
  item_count: number;
  converted_at: string | null;
  shipping_method_id: string | null;
  item_total: string | null;
  display_item_total: string | null;
  items: Array<Array<CartItem>>;
  billing_address: PallasTradeApiV3Address | null;
  shipping_address: PallasTradeApiV3Address | null;
  payment_methods: Array<PallasTradeApiV3PaymentMethod>;
  gift_card: unknown | null;
  store_credit: unknown | null;
}

export default PallasTradeApiV3ShoppingCart;
