// Typelizer digest 76460e65bbf79f4835e0d986a519ba78
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminCouponCode = {
  id: string;
  code: string;
  state: string | null;
  created_at: string;
  updated_at: string;
  promotion_id: string;
  order_id: string | null;
}

export default PallasTradeApiV3AdminCouponCode;
