// Typelizer digest 24049013bb4c5973ba43c9cdf5e1e8b9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminPayment, PallasTradeApiV3AdminReimbursement} from '@/types'

type PallasTradeApiV3AdminRefund = {
  id: string;
  transaction_id: string | null;
  state: string;
  amount: string | null;
  payment_id: string | null;
  refund_reason_id: string | null;
  reimbursement_id: string | null;
  metadata: Record<string, unknown>;
  last_error_message: string | null;
  requested_at: unknown;
  processing_at: unknown;
  succeeded_at: unknown;
  failed_at: unknown;
  ambiguous_at: unknown;
  created_at: string;
  updated_at: string;
  payment_split_id: unknown;
  target_order_id: unknown;
  payment?: PallasTradeApiV3AdminPayment;
  reimbursement?: PallasTradeApiV3AdminReimbursement;
}

export default PallasTradeApiV3AdminRefund;
