// Typelizer digest 599ccc93ad04f340e327a1cca55c8f85
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3ProductFilterCategoryOption = {
  id: string;
  name: string;
  permalink: string;
  count: number;
}

export default PallasTradeApiV3ProductFilterCategoryOption;
