// Typelizer digest 69f4438e443405589b24642ed17fd915
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3StockLocation = {
  id: string;
  state_abbr: string | null;
  name: string;
  address1: string | null;
  city: string | null;
  zipcode: string | null;
  country_iso: string | null;
  country_name: string | null;
  state_text: string | null;
}

export default PallasTradeApiV3StockLocation;
