// Typelizer digest 6a036ae248456af738d9dea41f0185f6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3PaymentMethod = {
  id: string;
  name: string;
  description: string | null;
  type: string;
  kind: string;
  frontend_kind: string;
  session_required: boolean;
  source_required: boolean;
  client_config: { provider: string, environment: string | null, publishable: Record<string, string>, session_token: string | null };
}

export default PallasTradeApiV3PaymentMethod;
