// Typelizer digest 1ec8f0bd37870b4b6d7637cafba50ad9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Refund = {
  id: string;
  transaction_id: string | null;
  state: string;
  amount: string | null;
  payment_id: string | null;
  refund_reason_id: string | null;
  reimbursement_id: string | null;
}

export default PallasTradeApiV3Refund;
