// Typelizer digest e11b1813e0f4aa64f38207ac65324163
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminStockLocation, PallasTradeApiV3AdminVariant} from '@/types'

type PallasTradeApiV3AdminStockItem = {
  id: string;
  count_on_hand: number;
  backorderable: boolean;
  stock_location_id: string | null;
  variant_id: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  allocated_count: number;
  available_count: number;
  stock_location?: PallasTradeApiV3AdminStockLocation;
  variant?: PallasTradeApiV3AdminVariant;
}

export default PallasTradeApiV3AdminStockItem;
