// Typelizer digest 7488599cf37e452a1f7987154b40e501
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProductFilterAvailabilityOption} from '@/types'

type PallasTradeApiV3ProductFilterAvailability = {
  id: string;
  type: 'availability';
  options: Array<ProductFilterAvailabilityOption>;
}

export default PallasTradeApiV3ProductFilterAvailability;
