// Typelizer digest 16a477db087bb9977849c3436834c0c8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminCustomField} from '@/types'

type PallasTradeApiV3AdminCategory = {
  id: string;
  name: string;
  permalink: string;
  position: number;
  depth: number;
  meta_title: string | null;
  meta_description: string | null;
  meta_keywords: string | null;
  children_count: number;
  parent_id: string | null;
  description: string;
  description_html: string;
  image_url: string | null;
  square_image_url: string | null;
  is_root: boolean;
  is_child: boolean;
  is_leaf: boolean;
  parent?: PallasTradeApiV3AdminCategory;
  children?: Array<PallasTradeApiV3AdminCategory>;
  ancestors?: Array<PallasTradeApiV3AdminCategory>;
  custom_fields?: Array<PallasTradeApiV3AdminCustomField>;
  translations?: Record<string, Record<string, string | number | null>>;
  metadata: Record<string, unknown>;
  pretty_name: string;
  lft: number;
  rgt: number;
  products_count: number;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminCategory;
