// Typelizer digest 7fd38453d6d72ca480375ee43f4582f3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminChannel = {
  id: string;
  name: string;
  code: string;
  active: boolean;
  default: boolean;
  preferred_order_routing_strategy: string | null;
  preferred_storefront_access: string | null;
  preferred_guest_checkout: boolean | null;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminChannel;
