// Typelizer digest 25fa5573eb917350b5caf48ea01899bb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminInvitation = {
  id: string;
  email: string;
  status: string;
  created_at: string;
  updated_at: string;
  expires_at: string;
  role_id: string;
  role_name: string;
  inviter_email: string;
  acceptance_url: string;
  invitee_exists: boolean;
  store: { id: string; name: string };
}

export default PallasTradeApiV3AdminInvitation;
