// Typelizer digest 36320a6c5c2e60ea3d975202f20cfc7b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminCustomField = {
  id: string;
  label: string;
  /** @deprecated Use `field_type` instead. The legacy `type` field returns the Ruby STI class name (e.g. `PallasTrade::Metafields::ShortText`) and will be removed in a future minor. */
  type: string;
  field_type: 'short_text' | 'long_text' | 'rich_text' | 'number' | 'boolean' | 'json';
  key: string;
  value: any;
  created_at: string;
  updated_at: string;
  storefront_visible: boolean;
  custom_field_definition_id: string;
}

export default PallasTradeApiV3AdminCustomField;
