// Typelizer digest 62db1bd19b6b09217689d30c424075a8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Post = {
  id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  author: string | null;
  seo_title: string | null;
  seo_description: string | null;
  published_at: string | null;
  cover_image_url: string | null;
  body: string | null;
  body_html: string | null;
}

export default PallasTradeApiV3Post;
