// Typelizer digest 446dc8fc5006926e3db4e3df5b3699b4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Price, PriceHistory, PallasTradeApiV3Media, PallasTradeApiV3OptionValue, PallasTradeApiV3CustomField} from '@/types'

type PallasTradeApiV3Variant = {
  id: string;
  product_id: string;
  sku: string | null;
  options_text: string;
  track_inventory: boolean;
  media_count: number;
  preorder_ships_at: string | null;
  thumbnail_url: string | null;
  purchasable: boolean;
  in_stock: boolean;
  backorderable: boolean;
  preorder: boolean;
  weight: number | null;
  height: number | null;
  width: number | null;
  depth: number | null;
  price: Price;
  original_price: Price | null;
  primary_media?: PallasTradeApiV3Media;
  media?: Array<PallasTradeApiV3Media>;
  option_values: Array<PallasTradeApiV3OptionValue>;
  custom_fields?: Array<PallasTradeApiV3CustomField>;
  prior_price?: PriceHistory | null;
}

export default PallasTradeApiV3Variant;
