// Typelizer digest ffe11fa31ca0f1c6da8d96fabf0f85cf
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3StockItem = {
  id: string;
  count_on_hand: number;
  backorderable: boolean;
  stock_location_id: string | null;
  variant_id: string | null;
}

export default PallasTradeApiV3StockItem;
