// Typelizer digest 27a1c1d644a74d3b6a13a4dd0823ab39
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3ProductFilterOptionValue = {
  id: string;
  name: string;
  label: string;
  position: number;
  color_code: string | null;
  image_url: string | null;
  count: number;
}

export default PallasTradeApiV3ProductFilterOptionValue;
