// Typelizer digest 65cc3f17990f7468789a49a2fb3f492d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3ProductPublication = {
  id: string;
  published_at: string | null;
  unpublished_at: string | null;
  product_id: string;
  channel_id: string;
}

export default PallasTradeApiV3ProductPublication;
