// Typelizer digest 29ea37df7c4d6ac9e3cc1d8a805eaad8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminDiscount = {
  id: string;
  promotion_id: string;
  name: string;
  description: string | null;
  code: string | null;
  amount: string;
  display_amount: string;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminDiscount;
