// Typelizer digest b13fd20a8528378c6712b1cd8e5d7f54
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {CreditCard, StoreCredit, PaymentSource, PallasTradeApiV3AdminPaymentMethod, PallasTradeApiV3AdminOrder, PallasTradeApiV3AdminRefund} from '@/types'

type PallasTradeApiV3AdminPayment = {
  id: string;
  payment_method_id: string;
  response_code: string | null;
  number: string;
  amount: string;
  display_amount: string;
  status: string;
  source_type: 'credit_card' | 'store_credit' | 'payment_source' | null;
  source_id: string | null;
  source: CreditCard | StoreCredit | PaymentSource | null;
  payment_method?: PallasTradeApiV3AdminPaymentMethod;
  metadata: Record<string, unknown>;
  avs_response: string | null;
  cvv_response_code: string | null;
  cvv_response_message: string | null;
  created_at: string;
  updated_at: string;
  captured_amount: string;
  order_id: string | null;
  order?: PallasTradeApiV3AdminOrder;
  refunds?: Array<PallasTradeApiV3AdminRefund>;
}

export default PallasTradeApiV3AdminPayment;
