// Typelizer digest 0f03df9e186f8170fd5efd801f1efb86
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3CreditCard = {
  id: string;
  brand: string;
  last4: string;
  month: number;
  year: number;
  name: string | null;
  default: boolean;
  gateway_payment_profile_id: string | null;
}

export default PallasTradeApiV3CreditCard;
