// Typelizer digest f18b713e2c00f86d22cc50c513b6ed6a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminContactMessage = {
  id: string;
  kind: string;
  name: string | null;
  email: string;
  subject: string | null;
  body: string;
  status: string;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminContactMessage;
