// Typelizer digest 9cf38b649477b94fe51d761b2adc6f89
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3DeliveryMethod, PallasTradeApiV3StockLocation, PallasTradeApiV3DeliveryRate} from '@/types'

type PallasTradeApiV3Fulfillment = {
  id: string;
  number: string;
  tracking: string | null;
  tracking_url: string | null;
  cost: string | null;
  display_cost: string | null;
  total: string | null;
  display_total: string | null;
  discount_total: string | null;
  display_discount_total: string | null;
  additional_tax_total: string | null;
  display_additional_tax_total: string | null;
  included_tax_total: string | null;
  display_included_tax_total: string | null;
  tax_total: string | null;
  display_tax_total: string | null;
  status: string;
  fulfillment_type: string;
  fulfilled_at: string | null;
  items: Array<{ item_id: string; variant_id: string; quantity: number }>;
  delivery_method: PallasTradeApiV3DeliveryMethod;
  stock_location: PallasTradeApiV3StockLocation;
  delivery_rates: Array<PallasTradeApiV3DeliveryRate>;
}

export default PallasTradeApiV3Fulfillment;
