// Typelizer digest b49b79a10f33727c3a1881b9d8f1f8d5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3DigitalLink = {
  id: string;
  access_counter: number;
  filename: string;
  content_type: string;
  download_url: string;
  authorizable: boolean;
  expired: boolean;
  access_limit_exceeded: boolean;
}

export default PallasTradeApiV3DigitalLink;
