// Typelizer digest 44690484d1663c3335e88ea51043ef93
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Invitation = {
  id: string;
  email: string;
  resource_type: string | null;
  inviter_type: string | null;
  invitee_type: string | null;
  created_at: string;
  updated_at: string;
  status: string;
  resource_id: string | null;
  inviter_id: string | null;
  invitee_id: string | null;
  role_id: string | null;
  expires_at: string | null;
  accepted_at: string | null;
}

export default PallasTradeApiV3Invitation;
