// Typelizer digest 4d456961857f2ded756839bb2d4f6939
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminPromotion = {
  id: string;
  name: string;
  description: string | null;
  code: string | null;
  starts_at: string | null;
  expires_at: string | null;
  usage_limit: number | null;
  match_policy: 'all' | 'any';
  path: string | null;
  kind: 'coupon_code' | 'automatic';
  multi_codes: boolean;
  number_of_codes: number | null;
  code_prefix: string | null;
  promotion_category_id: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  action_ids: Array<string>;
  rule_ids: Array<string>;
}

export default PallasTradeApiV3AdminPromotion;
