// Typelizer digest 1546a545bb189540afe397fc692537e0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminGiftCardBatch = {
  id: string;
  codes_count: number;
  currency: string | null;
  prefix: string | null;
  created_at: string;
  updated_at: string;
  amount: string | null;
  expires_at: string | null;
  created_by_id: string | null;
}

export default PallasTradeApiV3AdminGiftCardBatch;
