// Typelizer digest 88dede06b4c0ac9de8b43ecffd0dc37b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminPromotionRedemption = {
  id: string;
  state: string;
  currency: string | null;
  release_reason: string | null;
  promotion_id: string | null;
  order_id: string | null;
  user_id: string | null;
  coupon_code: string | null;
  amount: string | null;
  display_amount: string | null;
  reserved_at: string | null;
  reserved_until: string | null;
  committed_at: string | null;
  released_at: string | null;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminPromotionRedemption;
