// Typelizer digest 9d122ba45dc6f3e4d9bcbb5c954b1d28
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3ReturnAuthorization = {
  id: string;
  number: string;
  status: string;
  order_id: string | null;
  stock_location_id: string | null;
  return_authorization_reason_id: string | null;
}

export default PallasTradeApiV3ReturnAuthorization;
