// Typelizer digest 530281da97685adf600feb731d24f605
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3Address, PallasTradeApiV3LineItem, PallasTradeApiV3Fulfillment} from '@/types'

type PallasTradeApiV3StoreCheckoutCheckout = {
  id: string;
  number: string;
  state: string;
  status: string;
  payment_state: string | null;
  shipment_state: string | null;
  email: string | null;
  currency: string;
  submitted_at: string | null;
  completed_at: string | null;
  version: number;
  price_version: string | null;
  ready: boolean;
  missing_requirements: Array<string>;
  expires_at: string | null;
  item_total: string | null;
  display_item_total: string | null;
  delivery_total: string | null;
  display_delivery_total: string | null;
  adjustment_total: string | null;
  display_adjustment_total: string | null;
  discount_total: string | null;
  display_discount_total: string | null;
  tax_total: string | null;
  display_tax_total: string | null;
  included_tax_total: string | null;
  display_included_tax_total: string | null;
  additional_tax_total: string | null;
  display_additional_tax_total: string | null;
  total: string | null;
  display_total: string | null;
  amount_due: string | null;
  display_amount_due: string | null;
  shipping_address: PallasTradeApiV3Address | null;
  billing_address: PallasTradeApiV3Address | null;
  items: Array<PallasTradeApiV3LineItem>;
  fulfillments: Array<PallasTradeApiV3Fulfillment>;
  discounts: Array<{ id: string, promotion_id: string, name: string, description: string | null, code: string | null, kind: string, amount: string | null, display_amount: string | null, breakdown: { items: string, order: string, shipping: string } | null, removable: boolean }>;
  taxes: Array<{ id: string, amount: string | null, currency: string }>;
  credits: { gift_cards: Array<{ id: string, code: string, amount: string | null, display_amount: string | null }>, store_credit: { amount: string | null, display_amount: string | null } | null };
  capabilities: { can_edit_address: boolean, can_change_shipping: boolean, can_apply_promotion: boolean, can_pay: boolean };
  billing_mode: string;
  payment: { available_payment_methods: Array<{ id: string, name: string, description: string | null, type: string, session_required: boolean, source_required: boolean, kind: string, frontend_kind: string, option_id: string, method_key: string, display_name: string, group: string, position: number, entries: Array<{ option_id: string, method_key: string, display_name: string, frontend_kind: string, group: string, position: number }>, requires_authentication: boolean, client_config: { provider: string, environment: string | null, publishable: Record<string, string>, session_token: string | null } }> };
}

export default PallasTradeApiV3StoreCheckoutCheckout;
