// Typelizer digest 599506d0d707e02dd6e9401a65ed3e07
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminRedirect = {
  id: string;
  from_path: string;
  to_path: string;
  status_code: integer;
  active: boolean;
  title: string | null;
  description: string | null;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminRedirect;
