// Typelizer digest 286ce7b0dc79cdd96fcb20e53923208b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3PaymentMethod = {
  id: string;
  name: string;
  description: string | null;
  type: string;
  kind: string;
  frontend_kind: string;
  session_required: boolean;
  option_id: string;
  method_key: string;
  display_name: string;
  source_required: boolean;
  client_config: { provider: string, environment: string | null, publishable: Record<string, string>, session_token: string | null };
}

export default PallasTradeApiV3PaymentMethod;
