// Typelizer digest 3b2a4b38a573d8f5b052b86576ebb071
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Reimbursement = {
  id: string;
  number: string;
  reimbursement_status: string | null;
  total: string | null;
  order_id: string | null;
  customer_return_id: string | null;
}

export default PallasTradeApiV3Reimbursement;
