// Typelizer digest cf4ad3f61c59662a2f121ef6a11db513
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminCustomer} from '@/types'

type PallasTradeApiV3AdminCustomerGroup = {
  id: string;
  name: string;
  description: string | null;
  customers_count: number;
  created_at: string;
  updated_at: string;
  customers?: Array<PallasTradeApiV3AdminCustomer>;
}

export default PallasTradeApiV3AdminCustomerGroup;
