// Typelizer digest 7458d939de96b31964ca977ccff76739
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3PriceHistory = {
  id: string;
  amount: string;
  amount_in_cents: number;
  currency: string;
  display_amount: string;
  recorded_at: string;
}

export default PallasTradeApiV3PriceHistory;
