// Typelizer digest 75e336a54e0a23570eaf6829e22c46d0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3Discount, PallasTradeApiV3LineItem, PallasTradeApiV3Fulfillment, PallasTradeApiV3Payment, PallasTradeApiV3PaymentMethod, PallasTradeApiV3Address, PallasTradeApiV3GiftCard, PallasTradeApiV3Market} from '@/types'

type PallasTradeApiV3Order = {
  id: string;
  market_id: string | null;
  channel_id: string | null;
  number: string;
  email: string;
  customer_note: string | null;
  currency: string;
  locale: string | null;
  total_quantity: number;
  parent_id: string | null;
  children_ids: Array<string>;
  is_parent: boolean;
  is_child: boolean;
  is_single: boolean;
  state: string;
  status: string;
  submitted_at: string | null;
  completed_at: string | null;
  cart_id: string | null;
  fulfillment_status: string | null;
  payment_status: string | null;
  item_total: string | null;
  display_item_total: string | null;
  adjustment_total: string | null;
  display_adjustment_total: string | null;
  discount_total: string | null;
  display_discount_total: string | null;
  tax_total: string | null;
  display_tax_total: string | null;
  included_tax_total: string | null;
  display_included_tax_total: string | null;
  additional_tax_total: string | null;
  display_additional_tax_total: string | null;
  gift_card_total: string | null;
  display_gift_card_total: string | null;
  delivery_total: string | null;
  display_delivery_total: string | null;
  total: string | null;
  display_total: string | null;
  amount_due: string | null;
  display_amount_due: string | null;
  store_credit_total: string | null;
  display_store_credit_total: string | null;
  covered_by_store_credit: boolean;
  discounts: Array<PallasTradeApiV3Discount>;
  items: Array<PallasTradeApiV3LineItem>;
  fulfillments: Array<PallasTradeApiV3Fulfillment>;
  payments: Array<PallasTradeApiV3Payment>;
  payment_methods: Array<PallasTradeApiV3PaymentMethod>;
  billing_address: PallasTradeApiV3Address | null;
  shipping_address: PallasTradeApiV3Address | null;
  gift_card: PallasTradeApiV3GiftCard | null;
  market: PallasTradeApiV3Market | null;
}

export default PallasTradeApiV3Order;
