// Typelizer digest 8f188851c52349150aa1787a7738419c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3Address} from '@/types'

type PallasTradeApiV3Customer = {
  id: string;
  email: string;
  first_name: string | null;
  last_name: string | null;
  phone: string | null;
  accepts_email_marketing: boolean;
  full_name: string;
  available_store_credit_total: string;
  display_available_store_credit_total: string;
  addresses: Array<PallasTradeApiV3Address>;
  default_billing_address: PallasTradeApiV3Address | null;
  default_shipping_address: PallasTradeApiV3Address | null;
}

export default PallasTradeApiV3Customer;
