// Typelizer digest 958a8b29a05234fd595d58d761e65c68
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Price, PriceHistory, PallasTradeApiV3AdminMedia, PallasTradeApiV3AdminOptionValue, PallasTradeApiV3AdminCustomField, PallasTradeApiV3AdminPrice, PallasTradeApiV3AdminStockItem} from '@/types'

type PallasTradeApiV3AdminVariant = {
  id: string;
  product_id: string;
  sku: string | null;
  options_text: string;
  track_inventory: boolean;
  media_count: number;
  preorder_ships_at: string | null;
  thumbnail_url: string | null;
  purchasable: boolean;
  in_stock: boolean;
  backorderable: boolean;
  preorder: boolean;
  weight: number | null;
  height: number | null;
  width: number | null;
  depth: number | null;
  price: Price;
  original_price: Price | null;
  primary_media?: PallasTradeApiV3AdminMedia;
  media?: Array<PallasTradeApiV3AdminMedia>;
  option_values: Array<PallasTradeApiV3AdminOptionValue>;
  custom_fields?: Array<PallasTradeApiV3AdminCustomField>;
  prior_price?: PriceHistory | null;
  metadata: Record<string, unknown>;
  position: number;
  cost_price: string | null;
  cost_currency: string | null;
  barcode: string | null;
  weight_unit: string | null;
  dimensions_unit: string | null;
  backorder_limit: number | null;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
  preorderable: boolean;
  tax_category_id: string | null;
  available_stock: number | null;
  reserved_quantity: number;
  total_on_hand: number | null;
  product_name: string;
  prices?: Array<PallasTradeApiV3AdminPrice>;
  stock_items?: Array<PallasTradeApiV3AdminStockItem>;
}

export default PallasTradeApiV3AdminVariant;
