// Typelizer digest 1a34ce8b4206ca70e7da3dc67e58a6a9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3DeliveryMethod = {
  id: string;
  name: string;
  code: string | null;
}

export default PallasTradeApiV3DeliveryMethod;
