// Typelizer digest 588c40cca131690b4b5b551b31682edd
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Review = {
  id: string;
  product_id: string | null;
  user_name: string | null;
  image_urls: Array<string>;
  helpful_votes_count: number;
  helpful_voted: boolean | null;
  rating: number;
  title: string | null;
  body: string | null;
  verified_purchase: boolean;
  created_at: string | null;
}

export default PallasTradeApiV3Review;
