// Typelizer digest 8c71ea1f9eba401496c23dbcc50e1b35
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminVariant} from '@/types'

type PallasTradeApiV3AdminPrice = {
  id: string;
  amount: string | null;
  amount_in_cents: number | null;
  compare_at_amount: string | null;
  compare_at_amount_in_cents: number | null;
  currency: string | null;
  display_amount: string | null;
  display_compare_at_amount: string | null;
  price_list_id: string | null;
  price_list_ends_at: string | null;
  variant_id: string | null;
  created_at: string;
  updated_at: string;
  variant?: PallasTradeApiV3AdminVariant;
}

export default PallasTradeApiV3AdminPrice;
