// Typelizer digest a845e3c4af0fbadb234131029366b7d8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminPost = {
  id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  author: string | null;
  seo_title: string | null;
  seo_description: string | null;
  published_at: string | null;
  created_at: string;
  updated_at: string;
  status: string;
  cover_image_url: string | null;
  body: string | null;
  body_html: string | null;
}

export default PallasTradeApiV3AdminPost;
