// Typelizer digest 51fa8983f4fed6e0a03501ec85d063c9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminDiscount, PallasTradeApiV3AdminLineItem, PallasTradeApiV3AdminFulfillment, PallasTradeApiV3AdminPayment, PallasTradeApiV3AdminPaymentMethod, PallasTradeApiV3AdminAddress, PallasTradeApiV3AdminGiftCard, PallasTradeApiV3AdminMarket, PallasTradeApiV3AdminChannel, PallasTradeApiV3AdminStockLocation, PallasTradeApiV3AdminCustomer, PallasTradeApiV3AdminAdjustment, PallasTradeApiV3AdminReturnAuthorization, PallasTradeApiV3AdminReimbursement} from '@/types'

type PallasTradeApiV3AdminOrder = {
  id: string;
  market_id: string | null;
  channel_id: string | null;
  number: string;
  email: string;
  customer_note: string | null;
  currency: string;
  locale: string | null;
  total_quantity: number;
  parent_id: string | null;
  children_ids: Array<string>;
  is_parent: boolean;
  is_child: boolean;
  is_single: boolean;
  state: string;
  status: string;
  submitted_at: string | null;
  completed_at: string | null;
  cart_id: string | null;
  fulfillment_status: string | null;
  payment_status: string | null;
  item_total: string;
  display_item_total: string;
  adjustment_total: string;
  display_adjustment_total: string;
  discount_total: string;
  display_discount_total: string;
  tax_total: string;
  display_tax_total: string;
  included_tax_total: string;
  display_included_tax_total: string;
  additional_tax_total: string;
  display_additional_tax_total: string;
  gift_card_total: string;
  display_gift_card_total: string;
  delivery_total: string;
  display_delivery_total: string;
  total: string;
  display_total: string;
  amount_due: string;
  display_amount_due: string;
  store_credit_total: string;
  display_store_credit_total: string;
  covered_by_store_credit: boolean;
  discounts?: Array<PallasTradeApiV3AdminDiscount>;
  items?: Array<PallasTradeApiV3AdminLineItem>;
  fulfillments?: Array<PallasTradeApiV3AdminFulfillment>;
  payments?: Array<PallasTradeApiV3AdminPayment>;
  payment_methods?: Array<PallasTradeApiV3AdminPaymentMethod>;
  billing_address?: PallasTradeApiV3AdminAddress | null;
  shipping_address?: PallasTradeApiV3AdminAddress | null;
  gift_card: PallasTradeApiV3AdminGiftCard | null;
  market: PallasTradeApiV3AdminMarket | null;
  last_ip_address: string | null;
  considered_risky: boolean;
  confirmation_delivered: boolean;
  store_owner_notification_delivered: boolean;
  metadata: Record<string, unknown>;
  canceled_at: string | null;
  approved_at: string | null;
  created_at: string;
  updated_at: string;
  payment_total: string;
  display_payment_total: string;
  preferred_stock_location_id: string | null;
  tags: Array<string>;
  internal_note: string | null;
  approver_id: string | null;
  canceler_id: string | null;
  created_by_id: string | null;
  customer_id: string | null;
  channel?: PallasTradeApiV3AdminChannel;
  preferred_stock_location?: PallasTradeApiV3AdminStockLocation;
  customer?: PallasTradeApiV3AdminCustomer;
  approver?: PallasTradeApiV3AdminCustomer;
  canceler?: PallasTradeApiV3AdminCustomer;
  created_by?: PallasTradeApiV3AdminCustomer;
  adjustments?: Array<PallasTradeApiV3AdminAdjustment>;
  return_authorizations?: Array<PallasTradeApiV3AdminReturnAuthorization>;
  reimbursements?: Array<PallasTradeApiV3AdminReimbursement>;
}

export default PallasTradeApiV3AdminOrder;
