// Typelizer digest 1b6f2e508386c7ce8a73be62c36728e4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Locale = {
  code: string;
  name: string;
  default: boolean;
  rtl: boolean;
}

export default PallasTradeApiV3Locale;
