// Typelizer digest e4ab3f81882ec3ebf5144ac582dcee32
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3StoreCommerceTransaction = {
  id: string;
  state: string;
  purpose: string;
  currency: string;
  amount: string;
  checkout_version: number | null;
  price_version: string | null;
  snapshot_fingerprint: string | null;
  recovery_attempts: number;
  last_error_class: string | null;
  last_error_code: string | null;
  last_error_message: string | null;
  started_at: string | null;
  payment_confirmed_at: string | null;
  finalizing_at: string | null;
  completed_at: string | null;
  recovery_required_at: string | null;
  manual_review_at: string | null;
  canceled_at: string | null;
}

export default PallasTradeApiV3StoreCommerceTransaction;
