// Typelizer digest 31a6e5d3a6c1390c340786f95962ef92
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3State = {
  abbr: string;
  name: string;
}

export default PallasTradeApiV3State;
