// Typelizer digest 8b7dc8dc4c51eb2a7caad442708b0a30
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminPaymentSource = {
  id: string;
  gateway_payment_profile_id: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminPaymentSource;
