// Typelizer digest 1dbd431027eb7929c6e5c52490001680
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminCountry} from '@/types'

type PallasTradeApiV3AdminMarket = {
  id: string;
  name: string;
  currency: string;
  default_locale: string;
  tax_inclusive: boolean;
  default: boolean;
  country_isos: Array<string>;
  supported_locales: Array<string>;
  countries?: Array<PallasTradeApiV3AdminCountry>;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminMarket;
