// Typelizer digest a5ceea211dffe26b633fe6f0b299b00b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3CartItem = {
  id: string;
  variant_id: string;
  currency: string;
  quantity: number;
  selected: boolean;
  name: string;
  slug: string;
  options_text: string;
  unit_price: string | null;
  display_unit_price: string | null;
  amount: string | null;
  display_amount: string | null;
  thumbnail_url: string | null;
}

export default PallasTradeApiV3CartItem;
