// Typelizer digest bf65ca7f7320f05bd2fc4a5f8f794549
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminDeliveryMethod} from '@/types'

type PallasTradeApiV3AdminDeliveryRate = {
  id: string;
  delivery_method_id: string;
  name: string;
  selected: boolean;
  cost: string;
  total: string;
  additional_tax_total: string;
  included_tax_total: string;
  tax_total: string;
  display_cost: string;
  display_total: string;
  display_additional_tax_total: string;
  display_included_tax_total: string;
  display_tax_total: string;
  delivery_method?: PallasTradeApiV3AdminDeliveryMethod;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminDeliveryRate;
