// Typelizer digest 432db887cb544fa706583e8c2347761c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminDeliveryMethod = {
  id: string;
  name: string;
  code: string | null;
  display_estimated_price: string | null;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminDeliveryMethod;
