// Typelizer digest 35bcd864615ea2a02e5b74249c3abfe6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminCustomFieldDefinition = {
  id: string;
  namespace: string;
  key: string;
  label: string;
  field_type: 'short_text' | 'long_text' | 'rich_text' | 'number' | 'boolean' | 'json';
  resource_type: string;
  storefront_visible: boolean;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminCustomFieldDefinition;
