// Typelizer digest 4335dec6920f1a2de42b3dfbbe6ee0b3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminDeliveryMethod = {
  id: string;
  name: string;
  code: string | null;
  display_estimated_price: string | null;
  estimated_transit_business_days_min: number | null;
  estimated_transit_business_days_max: number | null;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminDeliveryMethod;
