// Typelizer digest 9215e0ccdc6b81163ee1c03dda230dbf
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProductFilterOptionValue} from '@/types'

type PallasTradeApiV3ProductFilterOption = {
  id: string;
  type: 'option';
  name: string;
  label: string;
  kind: string;
  options: Array<ProductFilterOptionValue>;
}

export default PallasTradeApiV3ProductFilterOption;
