// Typelizer digest 0cfb8b876bfded4920cd82d2eeb9aa91
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminDeliveryMethod, PallasTradeApiV3AdminStockLocation, PallasTradeApiV3AdminDeliveryRate, PallasTradeApiV3AdminOrder, PallasTradeApiV3AdminAdjustment} from '@/types'

type PallasTradeApiV3AdminFulfillment = {
  id: string;
  number: string;
  tracking: string | null;
  tracking_url: string | null;
  cost: string;
  display_cost: string;
  total: string;
  display_total: string;
  discount_total: string;
  display_discount_total: string;
  additional_tax_total: string;
  display_additional_tax_total: string;
  included_tax_total: string;
  display_included_tax_total: string;
  tax_total: string;
  display_tax_total: string;
  status: string;
  fulfillment_type: string;
  fulfilled_at: string | null;
  items: Array<{ item_id: string; variant_id: string; quantity: number }>;
  delivery_method?: PallasTradeApiV3AdminDeliveryMethod;
  stock_location?: PallasTradeApiV3AdminStockLocation;
  delivery_rates?: Array<PallasTradeApiV3AdminDeliveryRate>;
  metadata: Record<string, unknown>;
  adjustment_total: string;
  pre_tax_amount: string;
  created_at: string;
  updated_at: string;
  order_id: string | null;
  stock_location_id: string | null;
  order?: PallasTradeApiV3AdminOrder;
  adjustments?: Array<PallasTradeApiV3AdminAdjustment>;
}

export default PallasTradeApiV3AdminFulfillment;
