// Typelizer digest 3b08597f7503e99b9e900b5554ec51d3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {CartItem, PallasTradeApiV3Address, PallasTradeApiV3PaymentMethod} from '@/types'

type PallasTradeApiV3ShoppingCart = {
  id: string;
  token: string;
  status: string;
  email: string | null;
  customer_note: string | null;
  currency: string;
  locale: string | null;
  item_count: number;
  converted_at: string | null;
  shipping_method_id: string | null;
  item_total: string | null;
  display_item_total: string | null;
  items: Array<Array<CartItem>>;
  billing_address: PallasTradeApiV3Address | null;
  shipping_address: PallasTradeApiV3Address | null;
  payment_methods: Array<PallasTradeApiV3PaymentMethod>;
  discount_code: string | null;
  gift_card: { code: string, display_amount_remaining: string } | null;
  store_credit: { amount: string, display_amount: string } | null;
}

export default PallasTradeApiV3ShoppingCart;
