// Typelizer digest a92e1fa9ba49bcd70b886bcbddd40cb1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3GiftCardBatch = {
  id: string;
  codes_count: number;
  currency: string | null;
  prefix: string | null;
  created_at: string;
  updated_at: string;
  amount: string | null;
  expires_at: string | null;
  created_by_id: string | null;
}

export default PallasTradeApiV3GiftCardBatch;
