// Typelizer digest 3db4471dc6a056f38c67341f76a29928
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3PaymentMethod} from '@/types'

type PallasTradeApiV3PaymentSetupSession = {
  id: string;
  status: string;
  external_id: string | null;
  external_client_secret: string | null;
  external_data: Record<string, unknown>;
  payment_method_id: string | null;
  payment_source_id: string | null;
  payment_source_type: string | null;
  customer_id: string | null;
  payment_method: PallasTradeApiV3PaymentMethod;
}

export default PallasTradeApiV3PaymentSetupSession;
