// Typelizer digest aa799b436aa63880b38ce21cf2c9e5e9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3ProductFilterSortOption = {
  id: string;
}

export default PallasTradeApiV3ProductFilterSortOption;
