// Typelizer digest c34e09d2c82e8cc490d94fe4301cc8f8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {RefundCalculationLine, RefundCalculationPromotion, RefundCalculationTotals} from '@/types'

type PallasTradeApiV3AdminRefundCalculation = {
  id: string;
  order_id: string;
  currency: string | null;
  available: boolean;
  line_items: Array<RefundCalculationLine>;
  promotions: Array<RefundCalculationPromotion>;
  totals: RefundCalculationTotals;
}

export default PallasTradeApiV3AdminRefundCalculation;
