// Typelizer digest 9ee9cf6864a4c22e14bfcbdea7db481c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminStockReservation = {
  id: string;
  stock_item_id: string;
  line_item_id: string;
  order_id: string;
  variant_id: string | null;
  stock_location_id: string | null;
  quantity: number;
  expires_at: string;
  active: boolean;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminStockReservation;
