// Typelizer digest b0e414105a2af87010577a711df3ec35
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3ProductFilterAvailabilityOption = {
  id: 'in_stock' | 'out_of_stock';
  count: number;
}

export default PallasTradeApiV3ProductFilterAvailabilityOption;
