// Typelizer digest 788052445c9982e818651cb2d55bd002
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3CustomField = {
  id: string;
  label: string;
  /** @deprecated Use `field_type` instead. The legacy `type` field returns the Ruby STI class name (e.g. `PallasTrade::Metafields::ShortText`) and will be removed in a future minor. */
  type: string;
  field_type: 'short_text' | 'long_text' | 'rich_text' | 'number' | 'boolean' | 'json';
  key: string;
  value: any;
}

export default PallasTradeApiV3CustomField;
