// Typelizer digest 6e70d891d3bad373c8d4d16ecc9570f0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProductFilterPriceRange, ProductFilterAvailability, ProductFilterOption, ProductFilterCategory, ProductFilterSortOption} from '@/types'

type PallasTradeApiV3ProductFilters = {
  id: string;
  default_sort: string;
  total_count: number;
  filters: Array<ProductFilterPriceRange | ProductFilterAvailability | ProductFilterOption | ProductFilterCategory>;
  sort_options: Array<ProductFilterSortOption>;
}

export default PallasTradeApiV3ProductFilters;
