// Typelizer digest e500f45ed314aaf391461f1b6bb91162
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminStoreCreditCategory = {
  id: string;
  name: string;
  created_at: string;
  updated_at: string;
  non_expiring: boolean;
}

export default PallasTradeApiV3AdminStoreCreditCategory;
