// Typelizer digest 57a6a06d26118e37c899ef39128fefdd
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Review = {
  id: string;
  product_id: string | null;
  user_name: string | null;
  image_urls: Array<string>;
  rating: number;
  title: string | null;
  body: string | null;
  verified_purchase: boolean;
  created_at: string | null;
}

export default PallasTradeApiV3Review;
