// Typelizer digest 8199dd88a2a6e7d854ea4f2c8955c112
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3DeliveryMethod} from '@/types'

type PallasTradeApiV3DeliveryRate = {
  id: string;
  delivery_method_id: string;
  name: string;
  selected: boolean;
  cost: string;
  total: string;
  additional_tax_total: string;
  included_tax_total: string;
  tax_total: string;
  display_cost: string;
  display_total: string;
  display_additional_tax_total: string;
  display_included_tax_total: string;
  display_tax_total: string;
  delivery_method: PallasTradeApiV3DeliveryMethod;
}

export default PallasTradeApiV3DeliveryRate;
