// Typelizer digest 5d93472499e05153fd1305b66f5518f9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3WishlistItem} from '@/types'

type PallasTradeApiV3Wishlist = {
  id: string;
  name: string;
  token: string;
  is_default: boolean;
  is_private: boolean;
  items?: Array<PallasTradeApiV3WishlistItem>;
}

export default PallasTradeApiV3Wishlist;
