// Typelizer digest 95db29d1dec08056590308c5826c16a8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminRole = {
  id: string;
  name: string;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminRole;
