// Typelizer digest 2ddd3d253f89aa8da76aba8ecb168329
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Discount = {
  id: string;
  promotion_id: string;
  name: string;
  description: string | null;
  code: string | null;
  amount: string | null;
  display_amount: string | null;
}

export default PallasTradeApiV3Discount;
