// Typelizer digest a6e687895e94ad1ea377510f5426512d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Price, PriceHistory, PallasTradeApiV3Media, PallasTradeApiV3Variant, PallasTradeApiV3OptionType, PallasTradeApiV3OptionValue, PallasTradeApiV3Category, PallasTradeApiV3CustomField} from '@/types'

type PallasTradeApiV3Product = {
  id: string;
  name: string;
  slug: string;
  meta_title: string | null;
  meta_description: string | null;
  meta_keywords: string | null;
  variant_count: number;
  available_on: string | null;
  preorder_ships_at: string | null;
  purchasable: boolean;
  preorder: boolean;
  in_stock: boolean;
  backorderable: boolean;
  available: boolean;
  description: string | null;
  description_html: string | null;
  default_variant_id: string;
  thumbnail_url: string | null;
  tags: Array<string>;
  average_rating: number | null;
  review_count: number;
  price: Price;
  original_price: Price | null;
  primary_media?: PallasTradeApiV3Media;
  media?: Array<PallasTradeApiV3Media>;
  variants?: Array<PallasTradeApiV3Variant>;
  default_variant?: PallasTradeApiV3Variant;
  option_types?: Array<PallasTradeApiV3OptionType>;
  option_values?: Array<PallasTradeApiV3OptionValue>;
  categories?: Array<PallasTradeApiV3Category>;
  custom_fields?: Array<PallasTradeApiV3CustomField>;
  prior_price?: PriceHistory | null;
}

export default PallasTradeApiV3Product;
