// Typelizer digest c54023ea0e1fc108b3e2b3bf0037b55a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminMedia = {
  id: string;
  product_id: string | null;
  variant_ids: Array<string>;
  position: number;
  alt: string | null;
  media_type: string;
  focal_point_x: number | null;
  focal_point_y: number | null;
  external_video_url: string | null;
  original_url: string | null;
  mini_url: string | null;
  small_url: string | null;
  medium_url: string | null;
  large_url: string | null;
  xlarge_url: string | null;
  og_image_url: string | null;
  created_at: string;
  updated_at: string;
  viewable_id: string;
  download_url: string | null;
  metadata: Record<string, unknown>;
  viewable_type: string;
}

export default PallasTradeApiV3AdminMedia;
