// Typelizer digest 627ca0359f30745ce85f9a774121b5d4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminPayment, PallasTradeApiV3AdminReimbursement} from '@/types'

type PallasTradeApiV3AdminRefund = {
  id: string;
  transaction_id: string | null;
  amount: string | null;
  payment_id: string | null;
  refund_reason_id: string | null;
  reimbursement_id: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  payment?: PallasTradeApiV3AdminPayment;
  reimbursement?: PallasTradeApiV3AdminReimbursement;
}

export default PallasTradeApiV3AdminRefund;
