// Typelizer digest ffb5a65322f45e2b335accd9aa8f099b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminOrder, PallasTradeApiV3AdminStockLocation} from '@/types'

type PallasTradeApiV3AdminReturnAuthorization = {
  id: string;
  number: string;
  status: string;
  order_id: string | null;
  stock_location_id: string | null;
  return_authorization_reason_id: string | null;
  created_at: string;
  updated_at: string;
  order?: PallasTradeApiV3AdminOrder;
  stock_location?: PallasTradeApiV3AdminStockLocation;
}

export default PallasTradeApiV3AdminReturnAuthorization;
