// Typelizer digest 0e534058dadd57f9e8e7f31c5ae6994e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminTaxCategory = {
  id: string;
  name: string;
  tax_code: string | null;
  description: string | null;
  is_default: boolean;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminTaxCategory;
