// Typelizer digest 47d8948fe7177af4f0cb9b5052ad93d3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3Country} from '@/types'

type PallasTradeApiV3Market = {
  id: string;
  name: string;
  currency: string;
  default_locale: string;
  tax_inclusive: boolean;
  default: boolean;
  country_isos: Array<string>;
  supported_locales: Array<string>;
  countries?: Array<PallasTradeApiV3Country>;
}

export default PallasTradeApiV3Market;
