// Typelizer digest adaf1e5e60616db7f540ef43714ff8e2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3Address, PallasTradeApiV3LineItem, PallasTradeApiV3Fulfillment} from '@/types'

type PallasTradeApiV3StoreCheckoutCheckout = {
  id: string;
  number: string;
  state: string;
  status: string;
  payment_state: string | null;
  shipment_state: string | null;
  email: string | null;
  currency: string;
  submitted_at: string | null;
  completed_at: string | null;
  version: number;
  price_version: string | null;
  ready: boolean;
  missing_requirements: Array<string>;
  expires_at: string | null;
  item_total: string | null;
  display_item_total: string | null;
  delivery_total: string | null;
  display_delivery_total: string | null;
  adjustment_total: string | null;
  display_adjustment_total: string | null;
  discount_total: string | null;
  display_discount_total: string | null;
  tax_total: string | null;
  display_tax_total: string | null;
  included_tax_total: string | null;
  display_included_tax_total: string | null;
  additional_tax_total: string | null;
  display_additional_tax_total: string | null;
  total: string | null;
  display_total: string | null;
  amount_due: string | null;
  display_amount_due: string | null;
  shipping_address: PallasTradeApiV3Address | null;
  billing_address: PallasTradeApiV3Address | null;
  items: Array<PallasTradeApiV3LineItem>;
  fulfillments: Array<PallasTradeApiV3Fulfillment>;
  discounts: Array<{ id: string, promotion_id: string, name: string, description: string | null, code: string | null, kind: string, amount: string | null, display_amount: string | null, breakdown: { items: string, order: string, shipping: string } | null, removable: boolean }>;
  taxes: Array<{ id: string, amount: string | null, currency: string }>;
}

export default PallasTradeApiV3StoreCheckoutCheckout;
