// Typelizer digest 8c032d17c17e91a3297b8c877bc9f0ad
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminCreditCard = {
  id: string;
  brand: string;
  last4: string;
  month: number;
  year: number;
  name: string | null;
  default: boolean;
  gateway_payment_profile_id: string | null;
  customer_id: string | null;
  payment_method_id: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminCreditCard;
