// Typelizer digest 930d364b7778cc283b44802dcb227909
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3NewsletterSubscriber = {
  id: string;
  email: string;
  created_at: string;
  updated_at: string;
  verified: boolean;
  verified_at: string | null;
  customer_id: string | null;
}

export default PallasTradeApiV3NewsletterSubscriber;
