// Typelizer digest 82a5eab30644f00a1672ac7969c74e73
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminAllowedOrigin = {
  id: string;
  origin: string;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminAllowedOrigin;
