// Typelizer digest d8988a63c611ea28f65aa18b44ac258f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Base = {
  id: string;
}

export default PallasTradeApiV3Base;
