// Typelizer digest 6a912c218c58bf55d63bcf5919cdbadf
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProductFilterCategoryOption} from '@/types'

type PallasTradeApiV3ProductFilterCategory = {
  id: string;
  type: 'category';
  options: Array<ProductFilterCategoryOption>;
}

export default PallasTradeApiV3ProductFilterCategory;
