// Typelizer digest 6fe83534d5d1d7b7ca134dd26fadb096
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminProduct, PallasTradeApiV3AdminCategory, PallasTradeApiV3AdminCustomer, PallasTradeApiV3AdminCustomerGroup, PallasTradeApiV3AdminCountry, PallasTradeApiV3AdminChannel, PallasTradeApiV3AdminMarket} from '@/types'

type PallasTradeApiV3AdminPromotionRule = {
  id: string;
  created_at: string;
  updated_at: string;
  type: string;
  promotion_id: string;
  preferences: Record<string, unknown>;
  preference_schema: Array<{ key: string; type: string; default: unknown }>;
  label: string;
  product_ids: Array<string> | null;
  category_ids: Array<string> | null;
  customer_ids: Array<string> | null;
  products?: Array<PallasTradeApiV3AdminProduct>;
  categories?: Array<PallasTradeApiV3AdminCategory>;
  customers?: Array<PallasTradeApiV3AdminCustomer>;
  customer_groups?: Array<PallasTradeApiV3AdminCustomerGroup>;
  countries?: Array<PallasTradeApiV3AdminCountry>;
  channels?: Array<PallasTradeApiV3AdminChannel>;
  markets?: Array<PallasTradeApiV3AdminMarket>;
}

export default PallasTradeApiV3AdminPromotionRule;
