// Typelizer digest e5751bec556cf9180d967aa8d928f124
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3Variant} from '@/types'

type PallasTradeApiV3WishlistItem = {
  id: string;
  variant_id: string;
  wishlist_id: string;
  quantity: number;
  variant: PallasTradeApiV3Variant;
}

export default PallasTradeApiV3WishlistItem;
