// Typelizer digest 2b8242d5447d58a7f4a95c574d7b3b5a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminCustomer, PallasTradeApiV3AdminAdminUser, PallasTradeApiV3AdminGiftCardBatch, PallasTradeApiV3AdminOrder} from '@/types'

type PallasTradeApiV3AdminGiftCard = {
  id: string;
  code: string;
  status: string;
  currency: string;
  amount: string;
  amount_used: string;
  amount_authorized: string;
  amount_remaining: string;
  display_amount: string;
  display_amount_used: string;
  display_amount_remaining: string;
  expires_at: string | null;
  redeemed_at: string | null;
  expired: boolean;
  active: boolean;
  created_at: string;
  updated_at: string;
  customer_id: string | null;
  created_by_id: string | null;
  customer?: PallasTradeApiV3AdminCustomer;
  created_by?: PallasTradeApiV3AdminAdminUser;
  gift_card_batch?: PallasTradeApiV3AdminGiftCardBatch;
  orders?: Array<PallasTradeApiV3AdminOrder>;
}

export default PallasTradeApiV3AdminGiftCard;
