// Typelizer digest 764ab433535ef992599adbe228e3a1fe
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminStoreCredit = {
  id: string;
  amount: string;
  amount_used: string;
  amount_remaining: string;
  display_amount: string;
  display_amount_used: string;
  display_amount_remaining: string;
  currency: string;
  memo: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  customer_id: string | null;
  created_by_id: string | null;
  category_id: string | null;
  category_name: string | null;
}

export default PallasTradeApiV3AdminStoreCredit;
