// Typelizer digest 026338762e3bfaafe296d66a77677ce0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Media = {
  id: string;
  product_id: string | null;
  variant_ids: Array<string>;
  position: number;
  alt: string | null;
  media_type: string;
  focal_point_x: number | null;
  focal_point_y: number | null;
  external_video_url: string | null;
  original_url: string | null;
  mini_url: string | null;
  small_url: string | null;
  medium_url: string | null;
  large_url: string | null;
  xlarge_url: string | null;
  og_image_url: string | null;
}

export default PallasTradeApiV3Media;
