// Typelizer digest 9275290805e46ee17a1de84724a561c5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Promotion = {
  id: string;
  name: string;
  description: string | null;
  code: string | null;
}

export default PallasTradeApiV3Promotion;
