// Typelizer digest 545623cbb498248035d5d7b0411779bc
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3StockReservation = {
  id: string;
}

export default PallasTradeApiV3StockReservation;
