// Typelizer digest 7d56fcab80133a948d5728c4bb4ab9e0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Review = {
  id: string;
  product_id: string | null;
  user_name: string | null;
  rating: number;
  title: string | null;
  body: string | null;
  verified_purchase: boolean;
  created_at: string | null;
}

export default PallasTradeApiV3Review;
