// Typelizer digest c4d5007d352794aa899ee1d6d6932d9d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3TaxCategory = {
  id: string;
  name: string;
}

export default PallasTradeApiV3TaxCategory;
