// Typelizer digest 9104e958e4c5eceb074cf601663c0273
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminSetupTask} from '@/types'

type PallasTradeApiV3AdminStore = {
  id: string;
  metadata: Record<string, unknown>;
  name: string;
  code: string;
  preferred_storefront_url: string | null;
  default_currency: string;
  default_locale: string;
  mail_from_address: string | null;
  customer_support_email: string | null;
  new_order_notifications_email: string | null;
  preferred_send_consumer_transactional_emails: boolean;
  preferred_admin_locale: string | null;
  preferred_timezone: string;
  preferred_weight_unit: string;
  preferred_unit_system: string;
  preferred_storefront_access: string;
  preferred_guest_checkout: boolean;
  created_at: string;
  updated_at: string;
  url: string;
  api_url: string;
  setup_tasks: Array<PallasTradeApiV3AdminSetupTask>;
  supported_currencies: Array<string>;
  supported_locales: Array<string>;
  available_locales: Array<string>;
  logo_url: string | null;
  mailer_logo_url: string | null;
}

export default PallasTradeApiV3AdminStore;
