// Typelizer digest b69a34a3c97447921a172a2a0652e852
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminStockLocation} from '@/types'

type PallasTradeApiV3AdminStockTransfer = {
  id: string;
  number: string;
  reference: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  source_location_id: string | null;
  destination_location_id: string | null;
  source_location?: PallasTradeApiV3AdminStockLocation;
  destination_location?: PallasTradeApiV3AdminStockLocation;
}

export default PallasTradeApiV3AdminStockTransfer;
