// Typelizer digest ed9497888bd56792bfe896e27dd6210d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3OptionValue = {
  id: string;
  option_type_id: string;
  name: string;
  label: string;
  position: number;
  color_code: string | null;
  option_type_name: string;
  option_type_label: string;
  image_url: string | null;
}

export default PallasTradeApiV3OptionValue;
