// Typelizer digest c89d47032bfdbacfc0f424084d829ff5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminImportRow = {
  id: string;
  row_number: number;
  status: string;
  validation_errors: string | null;
  item_type: string | null;
  created_at: string;
  updated_at: string;
  import_id: string | null;
  item_id: string | null;
  data: Record<string, string | null>;
}

export default PallasTradeApiV3AdminImportRow;
