// Typelizer digest 0e966a503acf8b481f31868405827fff
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminDigitalLink = {
  id: string;
  access_counter: number;
  filename: string;
  content_type: string;
  download_url: string;
  authorizable: boolean;
  expired: boolean;
  access_limit_exceeded: boolean;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminDigitalLink;
