// Typelizer digest bb7bb72dab3a3f056aaf45d96468b737
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Policy = {
  id: string;
  name: string;
  slug: string;
  body: string | null;
  body_html: string | null;
}

export default PallasTradeApiV3Policy;
