// Typelizer digest 6a0863be0d450deb916b10d766d8066e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3ProductFilterPriceRange = {
  id: string;
  type: 'price_range';
  min: number;
  max: number;
  currency: string;
}

export default PallasTradeApiV3ProductFilterPriceRange;
