// Typelizer digest f96d3bf896667e9b0f0532f30532b389
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3StoreCredit = {
  id: string;
  amount: string;
  amount_used: string;
  amount_remaining: string;
  display_amount: string;
  display_amount_used: string;
  display_amount_remaining: string;
  currency: string;
}

export default PallasTradeApiV3StoreCredit;
