// Typelizer digest 0f2f75699458656b1e885eb5aefbe8c9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminPaymentCombination = {
  id: string;
  status: string;
  currency: string;
  created_at: string | null;
  member_count: number;
  amount: string;
  refunded_total: string;
  members?: unknown;
  payments?: unknown;
  transaction?: unknown;
}

export default PallasTradeApiV3AdminPaymentCombination;
