// Typelizer digest 47e8ca2b3d9a540f73cac6ca2cf71b38
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3ShippingCategory = {
  id: string;
  name: string;
}

export default PallasTradeApiV3ShippingCategory;
