// Typelizer digest 1425e67c11cb6e7cebc865510efbb813
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Price = {
  id: string;
  amount: string | null;
  amount_in_cents: number | null;
  compare_at_amount: string | null;
  compare_at_amount_in_cents: number | null;
  currency: string | null;
  display_amount: string | null;
  display_compare_at_amount: string | null;
  price_list_id: string | null;
}

export default PallasTradeApiV3Price;
