// Typelizer digest fcc72bd956e3fa95b64d3198790e7399
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3ImportRow = {
  id: string;
  row_number: number;
  status: string;
  validation_errors: string | null;
  item_type: string | null;
  created_at: string;
  updated_at: string;
  import_id: string | null;
  item_id: string | null;
}

export default PallasTradeApiV3ImportRow;
