// Typelizer digest 67b2372321c6ae48e2c04d61e8b6bfbb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminMarket, PallasTradeApiV3AdminCustomerGroup, PallasTradeApiV3AdminChannel, PallasTradeApiV3AdminCustomer} from '@/types'

type PallasTradeApiV3AdminPriceRule = {
  id: string;
  created_at: string;
  updated_at: string;
  type: string;
  price_list_id: string;
  preferences: Record<string, unknown>;
  preference_schema: Array<{ key: string; type: string; default: unknown }>;
  label: string;
  description: string | null;
  markets?: Array<PallasTradeApiV3AdminMarket>;
  customer_groups?: Array<PallasTradeApiV3AdminCustomerGroup>;
  channels?: Array<PallasTradeApiV3AdminChannel>;
  customers?: Array<PallasTradeApiV3AdminCustomer>;
}

export default PallasTradeApiV3AdminPriceRule;
