// Typelizer digest 5a9f2c9804e445ffc046f65d419e503b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3ContactMessage = {
  id: string;
  kind: string;
  name: string | null;
  email: string;
  subject: string | null;
  body: string;
  status: string;
  created_at: string;
}

export default PallasTradeApiV3ContactMessage;
