// Typelizer digest 06629efff2207e7a804d1469754ea7d5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3Price = {
  id: string;
  amount: string | null;
  amount_in_cents: number | null;
  compare_at_amount: string | null;
  compare_at_amount_in_cents: number | null;
  currency: string | null;
  display_amount: string | null;
  display_compare_at_amount: string | null;
  price_list_id: string | null;
  price_list_ends_at: string | null;
}

export default PallasTradeApiV3Price;
