// Typelizer digest 7db5ab32f229e2b4d0f10a72808f258a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3ContactMessage = {
  id: string;
  kind: string;
  name: string | null;
  email: string;
  subject: string | null;
  body: string;
  status: string;
  created_at: iso8601;
}

export default PallasTradeApiV3ContactMessage;
