// Typelizer digest 29c35551a5bf556c7982008e7087b4da
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3ReturnItem = {
  id: string;
  reception_status: string | null;
  acceptance_status: string | null;
  created_at: string;
  updated_at: string;
  pre_tax_amount: string | null;
  included_tax_total: string | null;
  additional_tax_total: string | null;
  inventory_unit_id: string | null;
  return_authorization_id: string | null;
  customer_return_id: string | null;
  reimbursement_id: string | null;
  exchange_variant_id: string | null;
}

export default PallasTradeApiV3ReturnItem;
