// Typelizer digest ee97bd58d5685b1bed7569b35061cb39
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminDeliveryMethod = {
  id: string;
  name: string;
  code: string | null;
  created_at: string;
  updated_at: string;
}

export default PallasTradeApiV3AdminDeliveryMethod;
