// Typelizer digest 578cb5e057a02017865774f3a4e84b63
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3Order, PallasTradeApiV3PaymentSession} from '@/types'

type PallasTradeApiV3PaymentCombination = {
  id: string;
  status: string;
  currency: string;
  expires_at: string | null;
  completed_at: string | null;
  amount: string;
  orders?: Array<PallasTradeApiV3Order>;
  payment_session?: PallasTradeApiV3PaymentSession;
}

export default PallasTradeApiV3PaymentCombination;
