// Typelizer digest 4e8dac2bd4a2bcb3f75ab14faa58a5d3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3AdminPayment, PallasTradeApiV3AdminReimbursement} from '@/types'

type PallasTradeApiV3AdminRefund = {
  id: string;
  transaction_id: string | null;
  state: string;
  amount: string | null;
  payment_id: string | null;
  refund_reason_id: string | null;
  reimbursement_id: string | null;
  metadata: Record<string, unknown>;
  last_error_message: string | null;
  requested_at: unknown;
  processing_at: unknown;
  succeeded_at: unknown;
  failed_at: unknown;
  ambiguous_at: unknown;
  created_at: string;
  updated_at: string;
  payment_split_id: unknown;
  target_order_id: unknown;
  approval_status: string | null;
  payment?: PallasTradeApiV3AdminPayment;
  reimbursement?: PallasTradeApiV3AdminReimbursement;
}

export default PallasTradeApiV3AdminRefund;
