// Typelizer digest 02d6ac2e86288fcfe700a5764c2a1692
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3AdminImportMapping = {
  id: string;
  schema_field: string;
  file_column: string | null;
  required: boolean;
}

export default PallasTradeApiV3AdminImportMapping;
