// Typelizer digest a735586739c6c8bdc38232dd00e7b875
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type PallasTradeApiV3BackInStockSubscription = {
  id: string;
  product_id: string | null;
  variant_id: string | null;
  email: string;
  status: string;
  created_at: string;
}

export default PallasTradeApiV3BackInStockSubscription;
