// Typelizer digest 723fde84dfb0d96996f772c41af646eb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3Discount, PallasTradeApiV3LineItem, PallasTradeApiV3Fulfillment, PallasTradeApiV3Payment, PallasTradeApiV3Address, PallasTradeApiV3PaymentMethod, PallasTradeApiV3GiftCard, PallasTradeApiV3Market} from '@/types'

type PallasTradeApiV3Cart = {
  id: string;
  market_id: string | null;
  number: string;
  token: string;
  email: string | null;
  customer_note: string | null;
  currency: string;
  locale: string | null;
  total_quantity: number;
  warnings: Array<{code: string, message: string, line_item_id?: string, variant_id?: string}>;
  item_total: string | null;
  display_item_total: string | null;
  adjustment_total: string | null;
  display_adjustment_total: string | null;
  discount_total: string | null;
  display_discount_total: string | null;
  tax_total: string | null;
  display_tax_total: string | null;
  included_tax_total: string | null;
  display_included_tax_total: string | null;
  additional_tax_total: string | null;
  display_additional_tax_total: string | null;
  total: string | null;
  display_total: string | null;
  gift_card_total: string | null;
  display_gift_card_total: string | null;
  amount_due: string | null;
  display_amount_due: string | null;
  delivery_total: string | null;
  display_delivery_total: string | null;
  store_credit_total: string | null;
  display_store_credit_total: string | null;
  covered_by_store_credit: boolean;
  current_step: string;
  completed_steps: Array<string>;
  requirements: Array<{step: string, field: string, message: string}>;
  shipping_eq_billing_address: boolean;
  discounts: Array<PallasTradeApiV3Discount>;
  items: Array<PallasTradeApiV3LineItem>;
  fulfillments: Array<PallasTradeApiV3Fulfillment>;
  payments: Array<PallasTradeApiV3Payment>;
  billing_address: PallasTradeApiV3Address | null;
  shipping_address: PallasTradeApiV3Address | null;
  payment_methods: Array<PallasTradeApiV3PaymentMethod>;
  gift_card: PallasTradeApiV3GiftCard | null;
  market: PallasTradeApiV3Market | null;
}

export default PallasTradeApiV3Cart;
