// Typelizer digest 61ce67c5dac11a2a1693e8c953a3a8c9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PallasTradeApiV3PaymentMethod, PallasTradeApiV3Payment} from '@/types'

type PallasTradeApiV3PaymentSession = {
  id: string;
  status: string;
  currency: string;
  external_id: string;
  external_data: Record<string, unknown>;
  customer_external_id: string | null;
  expires_at: string | null;
  amount: string;
  payment_method_id: string;
  order_id: string;
  payment_method: PallasTradeApiV3PaymentMethod;
  payment?: PallasTradeApiV3Payment;
}

export default PallasTradeApiV3PaymentSession;
