# frozen_string_literal: true

# By placing all of PallasTrade's shared dependencies in this file and then loading
# it for each component's Gemfile, we can be sure that we're only testing just
# the one component of PallasTrade.
source 'https://rubygems.org'

gem 'rails', ENV.fetch('RAILS_VERSION', '~> 8.1.0'), require: false
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw]

platforms :jruby do
  gem 'jruby-openssl'
end

platforms :ruby do
  gem 'mysql2' if ENV['DB'] == 'mysql' || ENV['CI']
  gem 'pg' if ENV['DB'] == 'postgres' || ENV['CI']

  gem 'sqlite3', '>= 2.0'
end

group :test do
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'capybara-select-2'
  gem 'database_cleaner-active_record'
  gem 'email_spec'
  gem 'factory_bot_rails', '~> 6.2.0'
  gem 'jsonapi-rspec'
  gem 'multi_json'
  gem 'parallel_tests'
  gem 'rails-controller-testing'
  gem 'rspec-activemodel-mocks'
  gem 'rspec_junit_formatter'
  gem 'rspec-rails'
  gem 'rspec-retry'
  gem 'rswag-specs'
  gem 'shoulda-matchers', '~> 6.0'
  gem 'simplecov'
  gem 'stackprof'
  gem 'test-prof'
  gem 'timecop'
  gem 'webmock'
end

group :test, :development do
  gem 'awesome_print'
  gem 'brakeman'
  gem 'bundler-audit'
  gem 'ffaker'
  gem 'gem-release'
  gem 'i18n-tasks'
  gem 'license_finder'
  gem 'pry-byebug'
  gem 'puma'
  gem 'rubocop', '~> 1.0', require: false
  gem 'rubocop-rspec', require: false

  # Ruby 3.4+ removed observer from stdlib
  gem 'observer'
end

group :development do
  gem 'importmap-rails'
  # gem 'github_fast_changelog'
  gem 'ruby-lsp'
  gem 'ruby-lsp-rails'
  gem 'solargraph'
end

gem 'pallastrade', github: 'stevenbian9266-cyber/pallastrade', glob: 'pallastrade/**/*.gemspec'
gem 'pallastrade_admin', github: 'stevenbian9266-cyber/pallastrade', glob: 'pallastrade/**/*.gemspec'

gem 'propshaft' # needed for admin

gemspec
