source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'rails-controller-testing'

pallastrade_opts = if ENV['PALLASTRADE_GEMS_PATH']
                { 'path': ENV['PALLASTRADE_GEMS_PATH'] }
             else
                { 'github': 'stevenbian9266-cyber/pallastrade', 'branch': 'main', 'glob': 'pallastrade/**/*.gemspec' }
             end
gem 'pallastrade', pallastrade_opts

# pallastrade_admin pinned to the commit before pallastrade#14287, which added a
# PallasTrade::Admin::StorefrontController + `admin_storefront` route that collides
# with pallastrade_page_builder's. Revert to pallastrade_opts once the dependency conflict is resolved.
pallastrade_admin_opts = if ENV['PALLASTRADE_PATH']
                      { 'path': ENV['PALLASTRADE_PATH'] }
                   else
                      { 'github': 'stevenbian9266-cyber/pallastrade', 'ref': '2174f67734f523207bb90d6cdf4eb7463619af52', 'glob': 'pallastrade/admin/*.gemspec' }
                   end
gem 'pallastrade_admin', pallastrade_admin_opts

gem 'pallastrade_posts', github: 'stevenbian9266-cyber/pallastrade', branch: 'main'
gem 'pallastrade_legacy_product_properties', github: 'stevenbian9266-cyber/pallastrade', branch: 'main'
gem 'pallastrade_custom_domains', github: 'stevenbian9266-cyber/pallastrade', branch: 'main'

pallastrade_storefront_opts = { 'github': 'stevenbian9266-cyber/pallastrade', 'branch': 'main' }
gem 'pallastrade_page_builder', pallastrade_storefront_opts
gem 'pallastrade_storefront', pallastrade_storefront_opts

gem 'pallastrade_dev_tools', '>= 0.6.0.rc1'

if ENV['DB'] == 'mysql'
  gem 'mysql2'
elsif ENV['DB'] == 'postgres'
  gem 'pg'
else
  gem 'sqlite3'
end

gem 'propshaft'

gemspec
